// /app/api/get-exam-question/route.js

import OpenAI from 'openai';
import { NextResponse } from 'next/server';

export async function POST(request) {
    try {
        const { examType, difficulty, lawType } = await request.json();

        if (!examType || !difficulty || !lawType) {
            return NextResponse.json({ error: 'Incomplete exam configuration.' }, { status: 400 });
        }

        // Check if OPENAI_API_KEY is available
        if (!process.env.OPENAI_API_KEY) {
            console.error('OPENAI_API_KEY is not set.');
            return NextResponse.json(
                { error: 'Server configuration error: OpenAI API key is missing.' },
                { status: 500 }
            );
        }

        const openai = new OpenAI({
            apiKey: process.env.OPENAI_API_KEY,
        });

        // Define the prompt for the AI to generate a question
        const prompt = `
As an expert in ${lawType}, create a ${difficulty} level question suitable for the ${examType}. The question should focus on ${lawType} topics and adhere to the style of the ${examType}. Do not include the answer in your response.

Provide the question in plain text without any additional formatting.
`;

        const response = await openai.chat.completions.create({
            model: 'gpt-3.5-turbo',
            messages: [{ role: 'user', content: prompt }],
            max_tokens: 500,
            temperature: 0.7,
        });

        const assistantMessage = response.choices?.[0]?.message?.content.trim();

        // Log the assistant's message for debugging
        console.log('Generated Question:', assistantMessage);

        if (!assistantMessage) {
            throw new Error('No question generated by the AI.');
        }

        return NextResponse.json({ question: assistantMessage }, { status: 200 });
    } catch (error) {
        console.error('Error during OpenAI API call:', error.response?.data || error.message);
        return NextResponse.json(
            { error: 'Failed to generate exam question', details: error.response?.data || error.message },
            { status: 500 }
        );
    }
}
